apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-zxy6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ylyi-tenant/rhtap-demo-app/hacbs-test-project-zxy6@sha256:55e7feb482a45e1833c0ea4396aee64f2e45ae1e79f4fe137691177c6ec59512
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
