apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-zxy6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-zxy6
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-zxy6
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-zxy6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-zxy6
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ylyi-tenant/rhtap-demo-app/hacbs-test-project-zxy6@sha256:55e7feb482a45e1833c0ea4396aee64f2e45ae1e79f4fe137691177c6ec59512
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
